#theme: jekyll-theme-minimal
#title: Shricharan Baskaran
title: Shricharan Baskaran
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

github:
  repository_url: https://github.com/shricharandigic/
  linkedin: https://www.linkedin.com/in/shricharan/
